openapi: 3.0.2
info:
  title: TP-PRODUCT- Common Address Info schema
  description: Address Schema shared common by All API
  version: 1.0.0
paths: {}
components:
  schemas:
    Address:
      title: Address
      description: Section contains the party address details.
      type: object
      properties:
        line1:
          type: string
          minLength: 1
          maxLength: 35
          description: Lines 1 of the Name and Address field under the Party Section
        line2:
          type: string
          minLength: 1
          maxLength: 35
          description: Lines 2 of the Name and Address field under the Party Section
        line3:
          type: string
          minLength: 0
          maxLength: 35
          description: Lines3 of the Name and Address field under the Party Section
        contactName:
          type: string
          minLength: 0
          maxLength: 50
          description: Party Contact Person
        phoneNumber:
          type: string
          minLength: 0
          maxLength: 20
          description: Party Telephone number
        emailId:
          type: string
          minLength: 0
          maxLength: 512
          description: Party Email Id