openapi: 3.0.2
info:
  title: TP-PRODUCT- Common Amount Info schema
  description: Amount Schema shared common by All API
  version: 1.0.0
paths: {}
components:
  schemas:
    Amount:
      title: Amount
      type: object
      required:
        - currency
        - value
      properties:
        currency:
          $ref : 'Currency.yaml#/components/schemas/Currency'
        value:
          type: number
          format: double
          minLength: 0
          maxLength: 21
          description: Section contains the Amount in Transaction Amount (17,3)