openapi: 3.0.2
info:
  title: Query Lookup
  description: DSL for Query Lookup
  version: 1.0.0
paths: { }
components:
  schemas:
    QueryLookup:
      type: object
      required:
        - outputAttributes
      properties:
        outputAttributes:
          type: string
          format: string
        metaData:
          type: string