openapi: 3.0.0
info:
  title: Collection Data 
  description: 'Domain model Report Criteria'
  version: 1.0.0
paths: {}
components:
  schemas:
    CollectionData:
      title: CollectionData
      type: object
      properties:
        creationDate:
          $ref: '../global/Date.yaml#/components/schemas/Date'
        creationReference:
          type: string
        collectionDate:
          $ref: '../global/Date.yaml#/components/schemas/Date'
        collectionReference:
          type: string