openapi: 3.0.2
info:
  title: Match
  description: 'API specifications for Product'
  version: 1.0.0
paths:
  /product/{competitor_name}:
    post:
      tags:
        - Match
      description: Provides Match lookup capabilities
      operationId: matchLookUp
      requestBody:
        description: QueryLookup
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/QueryLookup.yaml'
      responses:
        '400':
          description: Bad Request
        '404':
          description: Match Not found
        '405':
          description: Validation Exception
        '500':
          description: Internal Server Error
