openapi: 3.0.2
apiVersion: 1.0.0
resourcePath: /match
produces:
  - application/json
info:
  title: Match Specifications
  description: 'API specifications for Match'
  version: 1.0.0
apis:
  - path: "/lookUp"
    operations:
      - method: POST
        summary: Provides match lookup for itemIds
        type:
        parameters:
          - name: body
            description: QueryLook Object with List of String parameter
            required: true
            allowMultiple: false
            type: QueryLookup
            paramType: body
        responseMessages:
          - code: 400
            message: Bad Request
          - code: 404
            message: Match Not found
          - code: 405
            message: Validation Exception
          - code: 500
            message: Internal Server Error
