openapi: 3.0.2
info:
  title: Product
  description: 'API specifications for Product'
  version: 1.0.0
paths:
  /product/{competitor_name}:
    post:
      tags:
        - Product
      description: Provides Product lookup capabilities
      operationId: productLookup
      parameters:
        - name: competitor_name
          in: path
          description: Competitor Name
          required: true
          schema:
            type: string
      requestBody:
        description: QueryLookup
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/QueryLookup.yaml#/components/schemas/QueryLookup'
      responses:
        '400':
          description: Bad Request
        '404':
          description: Match Not found
        '405':
          description: Validation Exception
        '500':
          description: Internal Server Error
  /product/{competitor_name}/{retailer_id}:
    get:
      tags:
        - Product
      description: Provides Product attributes details for Competitor and RetailerId
      operationId: productDetailsByCompetitorAndRetailerId
      parameters:
        - name: competitor_name
          in: path
          description: Competitor Name
          required: true
          schema:
            type: string
        - name: retailer_id
          in: path
          description: Retailer Id
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Bad Request
        '404':
          description: Match Not found
        '405':
          description: Validation Exception
        '500':
          description: Internal Server Error