openapi: 3.0.2
apiVersion: 1.0.0
resourcePath: /product
produces:
  - application/json
info:
  title: Product Specifications
  description: 'API specifications for Product'
  version: 1.0.0
apis:
  - path: "/{competitor_name}/{retailer_id}"
    operations:
      - method: GET
        summary: Provides Product attributes details for Competitor and RetailerId
        type:
        parameters:
          - name: body
            description: QueryLook Object with List of String parameter
            required: true
            allowMultiple: false
            type: QueryLookup
            produces:
              - application/json
            parameters:
              - name: competitor_name
                description: name of competitor
                required: true
                allowMultiple: false
                type: string
                paramtype: path
              - name: retailer_id
                description: name of retailer
                required: true
                allowMultiple: false
                type: string
                paramtype: path
              - in: header
                  name: MOCK_REQUEST
                  schema:
                    type: string
                  required: false
              - in: header
                  name: WM_CONSUMER.ID
                  schema:
                    type: string
                  required: false
              - in: header
                  name: WM_SVC.NAME
                  schema:
                    type: string
                  required: false
              - in: header
                  name: WM_SVC.VERSION
                  schema:
                    type: string
                  required: false
              - in: header
                  name: WM_SVC.ENV
                  schema:
                    type: string
                  required: false
              - in: header
                  name: WM_SEC.AUTH_SIGNATURE
                  schema:
                    type: string
                  required: false
              - in: header
                  name: WM_CONSUMER.INTIMESTAMP
                  schema:
                    type: string
                  required: false
              - in: header
                  name: WM_SEC.KEY_VERSION
                  schema:
                    type: string
                  required: false
        responseMessages:
          - code: 400
            message: Bad Request
          - code: 404
            message: Match Not found
          - code: 405
            message: Validation Exception
          - code: 500
            message: Internal Server Error
      - path: "/lookup/{competitor_name}"
          operations:
            - method: POST
              summary: Provides product lookup capabilities
              type:
              parameters:
                - name: body
                  description: QueryLook Object with List of String parameter
                  required: true
                  allowMultiple: false
                  type:
                    $ref: '../schemas/QueryLookup.yaml'
                  produces:
                    - application/json
                  parameters:
                    - name: competitor_name
                      description: name of competitor
                      required: true
                      allowMultiple: false
                      type: string
                      paramtype: path
                    - name: retailerId
                      description: name of retailer
                      required: true
                      allowMultiple: false
                      type: string
                      paramtype: path
                    - in: header
                        name: MOCK_REQUEST
                        schema:
                          type: string
                        required: false
                    - in: header
                        name: WM_CONSUMER.ID
                        schema:
                          type: string
                        required: false
                    - in: header
                        name: WM_SVC.NAME
                        schema:
                          type: string
                        required: false
                    - in: header
                        name: WM_SVC.VERSION
                        schema:
                          type: string
                        required: false
                    - in: header
                        name: WM_SVC.ENV
                        schema:
                          type: string
                        required: false
                    - in: header
                        name: WM_SEC.AUTH_SIGNATURE
                        schema:
                          type: string
                        required: false
                    - in: header
                        name: WM_CONSUMER.INTIMESTAMP
                        schema:
                          type: string
                        required: false
                    - in: header
                        name: WM_SEC.KEY_VERSION
                        schema:
                          type: string
                        required: false
              responseMessages:
                - code: 400
                  message: Bad Request
                - code: 404
                  message: Match Not found
                - code: 405
                  message: Validation Exception
                - code: 500
                  message: Internal Server Error
