/*
 * Taxation Domain Model
 * Domain model for Tax data for Reporting Engine
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package TaxStatement_;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDate;
/**
 * ReportData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-17T15:41:11.771529900+05:30[Asia/Calcutta]")
public class ReportData {
  @JsonProperty("reportStartDate")
  private LocalDate reportStartDate = null;

  @JsonProperty("reportEndDate")
  private LocalDate reportEndDate = null;

  public ReportData reportStartDate(LocalDate reportStartDate) {
    this.reportStartDate = reportStartDate;
    return this;
  }

   /**
   * Get reportStartDate
   * @return reportStartDate
  **/
  @Schema(description = "")
  public LocalDate getReportStartDate() {
    return reportStartDate;
  }

  public void setReportStartDate(LocalDate reportStartDate) {
    this.reportStartDate = reportStartDate;
  }

  public ReportData reportEndDate(LocalDate reportEndDate) {
    this.reportEndDate = reportEndDate;
    return this;
  }

   /**
   * Get reportEndDate
   * @return reportEndDate
  **/
  @Schema(description = "")
  public LocalDate getReportEndDate() {
    return reportEndDate;
  }

  public void setReportEndDate(LocalDate reportEndDate) {
    this.reportEndDate = reportEndDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportData reportData = (ReportData) o;
    return Objects.equals(this.reportStartDate, reportData.reportStartDate) &&
        Objects.equals(this.reportEndDate, reportData.reportEndDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reportStartDate, reportEndDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportData {\n");
    
    sb.append("    reportStartDate: ").append(toIndentedString(reportStartDate)).append("\n");
    sb.append("    reportEndDate: ").append(toIndentedString(reportEndDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
