/*
 * Taxation Domain Model
 * Domain model for Tax data for Reporting Engine
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package TaxStatement_;

import java.util.Objects;
import java.util.Arrays;
import TaxStatement_.Address;
import TaxStatement_.Amount;
import TaxStatement_.Currency;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * TaxData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-17T15:41:11.771529900+05:30[Asia/Calcutta]")
public class TaxData {
  @JsonProperty("clientId")
  private String clientId = null;

  @JsonProperty("dealId")
  private String dealId = null;

  @JsonProperty("address")
  private Address address = null;

  @JsonProperty("currency")
  private Currency currency = null;

  @JsonProperty("txnAmountCurrency")
  private Amount txnAmountCurrency = null;

  @JsonProperty("taxType")
  private String taxType = null;

  @JsonProperty("taxAmountCurrency")
  private Amount taxAmountCurrency = null;

  public TaxData clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/
  @Schema(description = "")
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public TaxData dealId(String dealId) {
    this.dealId = dealId;
    return this;
  }

   /**
   * Get dealId
   * @return dealId
  **/
  @Schema(description = "")
  public String getDealId() {
    return dealId;
  }

  public void setDealId(String dealId) {
    this.dealId = dealId;
  }

  public TaxData address(Address address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @Schema(description = "")
  public Address getAddress() {
    return address;
  }

  public void setAddress(Address address) {
    this.address = address;
  }

  public TaxData currency(Currency currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @Schema(description = "")
  public Currency getCurrency() {
    return currency;
  }

  public void setCurrency(Currency currency) {
    this.currency = currency;
  }

  public TaxData txnAmountCurrency(Amount txnAmountCurrency) {
    this.txnAmountCurrency = txnAmountCurrency;
    return this;
  }

   /**
   * Get txnAmountCurrency
   * @return txnAmountCurrency
  **/
  @Schema(description = "")
  public Amount getTxnAmountCurrency() {
    return txnAmountCurrency;
  }

  public void setTxnAmountCurrency(Amount txnAmountCurrency) {
    this.txnAmountCurrency = txnAmountCurrency;
  }

  public TaxData taxType(String taxType) {
    this.taxType = taxType;
    return this;
  }

   /**
   * Get taxType
   * @return taxType
  **/
  @Schema(description = "")
  public String getTaxType() {
    return taxType;
  }

  public void setTaxType(String taxType) {
    this.taxType = taxType;
  }

  public TaxData taxAmountCurrency(Amount taxAmountCurrency) {
    this.taxAmountCurrency = taxAmountCurrency;
    return this;
  }

   /**
   * Get taxAmountCurrency
   * @return taxAmountCurrency
  **/
  @Schema(description = "")
  public Amount getTaxAmountCurrency() {
    return taxAmountCurrency;
  }

  public void setTaxAmountCurrency(Amount taxAmountCurrency) {
    this.taxAmountCurrency = taxAmountCurrency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaxData taxData = (TaxData) o;
    return Objects.equals(this.clientId, taxData.clientId) &&
        Objects.equals(this.dealId, taxData.dealId) &&
        Objects.equals(this.address, taxData.address) &&
        Objects.equals(this.currency, taxData.currency) &&
        Objects.equals(this.txnAmountCurrency, taxData.txnAmountCurrency) &&
        Objects.equals(this.taxType, taxData.taxType) &&
        Objects.equals(this.taxAmountCurrency, taxData.taxAmountCurrency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientId, dealId, address, currency, txnAmountCurrency, taxType, taxAmountCurrency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaxData {\n");
    
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    dealId: ").append(toIndentedString(dealId)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    txnAmountCurrency: ").append(toIndentedString(txnAmountCurrency)).append("\n");
    sb.append("    taxType: ").append(toIndentedString(taxType)).append("\n");
    sb.append("    taxAmountCurrency: ").append(toIndentedString(taxAmountCurrency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
