openapi: 3.0.0
info:
  title: Report Data
  description: Domain model Report Criteria
  version: 1.0.0
paths: {}
components:
  schemas:
    ReportData:
      title: ReportData
      type: object
      properties:
        reportStartDate:
          $ref: '../global/Date.yaml#/components/schemas/Date'
        reportEndDate:
          $ref: '../global/Date.yaml#/components/schemas/Date'