openapi: 3.0.2
info:
  title: TP-PRODUCT- Common Date Info schema
  description: Date Schema shared common by All API
  version: 1.0.0
paths: {}
components:
  schemas:
    Date:
      type: string
      format: date
      minLength: 10
      maxLength: 10
      description: Date Field format should be YYYY-MM-dd
      example: 2018-01-25